name: Deploying app on WF
on:
  push:
    branches: [ Workflows ]
  pull_request:
    branches: [ Workflows ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt update
        sudo apt install ffmpeg
    - name: Run app
      continue-on-error: true
      run: |
        python -m main
